### ISSUE TITLE
incorrect icon launcher location

### ISSUE THREAD

**Issue by EricJohnsonL** [0tav/TestEmail2#1]
https://github.com/0tav/TestEmail2/tree/master/app/src/main:
-place icon launcher inside res/mipmap

**Comment by EricJohnsonL** [comment]
https://github.com/0tav/TestEmail2/blob/master/app/src/main/res/values/ic_launcher_background.xml
- initialize all color inside colors file only

**Comment by EricJohnsonL** [comment]
https://github.com/0tav/TestEmail2/blob/master/app/src/main/res/values/styles.xml

 <style name="item_sent_linear_layout"> --> follow naming from android,, like ItemSentLinearLayout

**Comment by EricJohnsonL** [comment]
https://github.com/0tav/TestEmail2/blob/master/app/src/main/java/com/example/ireos/testemail2/data/MailProvider.java

private int updateMail(Uri uri, ContentValues values,
                           String selection, String[] selectionArgs){
        if (values.containsKey(MailEntry.COLUMN_EMAIL_TO)){
            String emailTo = values.getAsString(MailEntry.COLUMN_EMAIL_TO);
            if (emailTo == null){
                throw new IllegalArgumentException("Requires email");
            }
        }

not emailTo==null, but !TextUtils.isEmpty(emailTo);

**Comment by EricJohnsonL** [comment]
https://github.com/0tav/TestEmail2/blob/master/app/src/main/res/layout/activity_sent.xml

RelativeLayout don't need orientation,

for naming the id:
-LinearLayout --> @+id/ll_(name)
-RelativeLayout--> @+id/rl_(name)
-button -->btn_
-textviews-->tv_
-edittext-->et_
-ImageView-->iv_
etc

**Comment by EricJohnsonL** [comment]
the purpose of provider?

**Comment by EricJohnsonL** [comment]
function of compose email?

**Comment by 0tav** [comment]
https://github.com/0tav/TestEmail2/tree/master/app/src/main/res/mipmap-hdpi

**Comment by 0tav** [comment]
https://github.com/0tav/TestEmail2/blob/master/app/src/main/java/com/example/ireos/testemail2/MailActivity.java

**Comment by 0tav** [comment]
https://github.com/0tav/TestEmail2/blob/master/app/src/main/java/com/example/ireos/testemail2/MailActivity.java

- compose function

**Comment by 0tav** [comment]
https://github.com/0tav/TestEmail2/tree/master/app/src/main/res/mipmap-hdpi

- icon launcher inside res/mipmap

**Comment by 0tav** [comment]
https://github.com/0tav/TestEmail2/blob/master/app/src/main/res/values/colors.xml

- ic background color inside res/color

**Comment by 0tav** [comment]
https://github.com/0tav/TestEmail2/blob/master/app/src/main/res/values/styles.xml

- fix style name 
<style name="ItemSentLinearLayout">

**Comment by 0tav** [comment]
https://github.com/0tav/TestEmail2/blob/master/app/src/main/java/com/example/ireos/testemail2/data/MailProvider.java

- fix updateMail & insertMail in MailProvider

**Comment by 0tav** [comment]
https://github.com/0tav/TestEmail2/blob/master/app/src/main/res/layout/activity_sent.xml
https://github.com/0tav/TestEmail2/blob/master/app/src/main/res/layout/activity_sent_edit.xml
https://github.com/0tav/TestEmail2/blob/master/app/src/main/res/layout/item_mail.xml

- fix naming id
